// Generates config.js from environment variables, so a prod deploy and a
// preview/test deploy (or a local dev run) can point at different Supabase
// projects without hand-editing a committed file.
//
// Deliberately non-breaking when the env vars aren't set: this runs as
// Vercel's buildCommand, and until PASSBOOK_SUPABASE_URL /
// PASSBOOK_SUPABASE_ANON_KEY are configured for an environment (Production /
// Preview) it must not fail that deploy — it just leaves whatever config.js
// is already committed in place. See docs/REFACTOR_PLAN.md Phase 0 (§0.3).
//
// It DOES fail loudly (non-zero exit) when the env vars are present but the
// key doesn't look like a Supabase "anon" key — the one mistake this guards
// against is a service_role key ending up in a file that ships to a browser.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = join(ROOT, "config.js");

const url = process.env.PASSBOOK_SUPABASE_URL;
const anonKey = process.env.PASSBOOK_SUPABASE_ANON_KEY;

if (!url || !anonKey) {
  console.log(
    "[build-config] PASSBOOK_SUPABASE_URL / PASSBOOK_SUPABASE_ANON_KEY not set — " +
    "leaving the existing config.js untouched."
  );
  process.exit(0);
}

function decodeJwtRole(jwt) {
  var parts = jwt.split(".");
  if (parts.length !== 3) return null;
  try {
    var payloadJson = Buffer.from(parts[1], "base64url").toString("utf8");
    var payload = JSON.parse(payloadJson);
    return payload.role || null;
  } catch {
    return null;
  }
}

const role = decodeJwtRole(anonKey);
if (role !== "anon") {
  console.error(
    "[build-config] Refusing to write config.js: PASSBOOK_SUPABASE_ANON_KEY's " +
    "JWT role is '" + role + "', not 'anon'. Never put a service_role key in a " +
    "browser-shipped file — double-check you copied the 'anon' / 'public' key " +
    "from Supabase Settings -> API."
  );
  process.exit(1);
}

const contents =
  "// AUTO-GENERATED by scripts/build-config.mjs from PASSBOOK_SUPABASE_URL /\n" +
  "// PASSBOOK_SUPABASE_ANON_KEY. Do not edit by hand — it will be overwritten\n" +
  "// on the next build. See config.example.js and README.md for local dev.\n" +
  "\n" +
  "window.PASSBOOK_CONFIG = {\n" +
  "  SUPABASE_URL: " + JSON.stringify(url) + ",\n" +
  "  SUPABASE_ANON_KEY: " + JSON.stringify(anonKey) + "\n" +
  "};\n";

writeFileSync(OUT_FILE, contents, "utf8");
console.log("[build-config] Wrote config.js for " + url);
